name: Cron Job
on:
  workflow_dispatch:
  repository_dispatch:
    types: [cron_job]
concurrency:
  group: ${{ github.workflow }}
jobs:
  cron-job:
    name: cron job
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Get dotenv
        run: echo ${{ secrets.DOTENV }} | base64 --decode > .env
      - name: Download & Install Sing-Box
        run: |
          wget -q https://github.com/SagerNet/sing-box/releases/download/v1.11.1/sing-box-1.11.1-linux-amd64.tar.gz -O sing-box.tar.gz
          tar -xzf sing-box.tar.gz
          sudo mv sing-box-1.11.1-linux-amd64/sing-box /usr/local/bin/sing-box
          sing-box version
      - name: Install dependencies
        run: |
          bun install
          bunx playwright install
      - name: Run bun
        run: bun start
      - name: Reset git history
        if: ${{ always() }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add temp/*
          git commit -m "update data"
          git push origin main
      - name: Call dispatch
        if: ${{always()}}
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: cron_job
