name: Cron Job
on:
  workflow_dispatch:
  repository_dispatch:
    types: [cron_job]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cron-job:
    name: cron job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Get dotenv
        run: echo ${{ secrets.DOTENV }} | base64 --decode > .env
      - name: Install dependencies
        run: bun install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: Compile to JS
        run: bunx tsc
      - name: Run bot
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          CI: "true"
        with:
          args: bun run start
      - name: Save temp data
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: '["./temp/user.json", "./temp/niks.json"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update temp data"
